config/routes.rb
Spaceart::Application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "faq" => "pages#faq"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="margin-left: 20px;" href="<%= root_path %>">Bitcoin SpaceArt</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "FAQ", faq_path %></a></li>
          
        </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitcoin Spaceart</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="google-site-verification" content="dGuRZY6ioTCgNvZRC9kpBxWvZE8skCkDCW52v1PbcTM" />

</head>
<body>
	<div id="wrap">
	<!--- Old Nav 
	<%= link_to "Home", root_path %>
	<%= link_to "About", about_path %>
	<%= link_to "Contact", contact_path %> -->
<%= render 'layouts/header' %>
<%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52168434-1', 'bitcoinspaceart.com');
  ga('send', 'pageview');

</script>

<div id="google">
	<a href="https://plus.google.com/116322423792936545197" rel="publisher">Google+</a>
</div>

<!-- Google Code for Remarketing Tag -->

<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 969632363;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/969632363/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


</div>

<div id="footer">
      <div class="container">
        <p class="text-muted credit">Bitcoin SpaceArt: Established 2014.</p>
        <ul>
        	<li><a href="http://www.bitcoinspaceart.com/about">About Bitcoin SpaceArt</a></li>
        	<li><a href="http://www.bitcoinspaceart.com/faq">Frequently Asked Questions</a></li>
        	<li><a href="http://www.bitcoinspaceart.com/contact">Need Help? Contact Us</a></li>
        </ul>
        <div id="twitterbutton">
        	<a href="https://twitter.com/BitcoinSpaceArt" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @BitcoinSpaceArt</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
		</div>
      </div>
 </div>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<div class="jumbotron">
		<div class="aboutText"> 
			<h1>Bitcoin SpaceArt Project</h1>
			<p>As two Bitcoin hobbyists based out of Ann Arbor, MI, we decided to combine our interest in art and cryptocurrency by selling <a href="http://www.chancetimeart.com/">Chancetime's</a> BTC-themed artwork.</p> 
			<div class="aboutimage">
				<%= image_tag("bitcoin2.jpg", :alt => "rss feed", :class => "style_image") %>
			</div>

			<p>Each piece is a one-of-a-kind homage to the world's foremost cryptocurrency, created on 16" x 18" posterboard. While no two Bitcoin SpaceArt pieces are identical, you can see a mock-up of the design on our home page.</p>  
			<p>The Bitcoin SpaceArt piece can be yours for $25 USD, paid for exclusively in Bitcoin using Coinbase's wallet system. While we currently can only serve customers in the United States, our shipping is free with your order. Woohoo!</p>

			<div class="imagecontainer"> 
				<%= image_tag("bitcoin5.jpg", :alt => "rss feed", :class => "style_image") %>
			</div>
			<p>Estimated shipping time will be in five days of your order. We will send a confirmation email upon receiving your order.</p> 
			<p>We are extremely stoked to be working with Bitcoin. Let us know what you think or follow us on <a href="https://twitter.com/bitcoinspaceart">Twitter</a> 

<!--- WE MAY WANT TO PUT A BUTTON HERE TO GAUGE INTERNATIONAL INTEREST IN THE LONG-TERM. CLICK HERE TO ADD YOUR NAME --> 

	</div> 
	</div>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<div class="jumbotron">
		<div id="contact">
		<h1>Beam Me Up: Contact Bitcoin SpaceArt</h1> 
		<p>Thank you for visiting Bitcoin SpaceArt.</p>
		<div class="imagecontainer"> 
				<%= image_tag("bitcoin2.jpg", :alt => "rss feed", :class => "faq_image") %>
		</div>
		<p>If you have questions or need some information about your order, get in touch with us!</p>
		<ul> 
			<li>Email: bitcoinspaceart [at] gmail [dot] com</li>
			<li><a href="https://twitter.com/bitcoinspaceart">@BitcoinSpaceart</a></li>
			<li><a href="https://plus.google.com/b/116322423792936545197/116322423792936545197/about">Google+</a></li>
		</ul>
		<p>We will make sure to get back to you. Let us know what you think about our project, and make sure to follow us on <a href="https://twitter.com/bitcoinspaceart">Twitter</a>.
		</div> 

<!-- Doing tags with the Bitcoin symbol --> 

<!--- Two BTC hobbyists who live in A2. Tell them how to get in touch with you. --> 

<!--- We will give refunds if they are damaged. Put some information down about the refund policy in case something happens with the order.  --> 

	</div> 
</div>

app/views/pages/faq.html.erb
<div class="container">
	<div class="jumbotron">
		<div class="aboutText">
		<h1>Frequently Asked Questions</h1> 
		<p style="font-size: 23px;">Will all SpaceArt portraits look the same?</p>
		<p style="margin-left: 15px;">No, each SpaceArt project will be unique to the order. That said, as you can see throughout the site, we maintain a Bitcoin theme inspired by the community's "to the moon" slogan.</p> 
		<div class="imagecontainer"> 
				<%= image_tag("bitcoin3.jpg", :alt => "rss feed", :class => "faq_image") %>
		</div>
		<p style="font-size: 23px;">What are the shipping costs for each order?</p>
		<p style="margin-left: 15px;">Shipping costs are included with your order, as long as you live in the United States. We are not shipping international yet, though we would love to. If you are interested, definitely let us know so we can gauge our international interest.</p> 

		<div class="imagecontainer"> 
				<%= image_tag("bitcoin5.jpg", :alt => "rss feed", :class => "style_image") %>
		</div>

		<p style="font-size: 23px;">What if there is a problem with my order?</p>
		<p style="margin-left: 15px;">We are members of the Bitcoin community, and we want to make sure every customer is fully satisfied. If your artwork is damaged in the mailing process or another issue arises, please let us know immediately. Click the <a href="/contact">contact button</a> to let us know right away, and we'll make sure to reach out to you.</p>
	</div>
</div>
</div> 

app/views/pages/home.html.erb
<div class="container">
	<div class="jumbotron">
		
		<div class="last">
			<p>Bringing Bitcoin to the Moon</p> 
		</div> 

		<!--  Carousel - consult the Twitter Bootstrap docs at 
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <div class="imagecontainer"> 
				<%= image_tag("bitcoin7.jpg", :alt => "rss feed", :class => "style_image") %>
		</div> 
    </div>
    
    <div class="item">
      <div class="imagecontainer"> 
				<%= image_tag("bitcoin8.jpg", :alt => "rss feed", :class => "style_image") %>
		</div> 
    </div>
    <div class="item">
      <div class="imagecontainer"> 
				<%= image_tag("bitcoin9.jpg", :alt => "rss feed", :class => "style_image") %>
		</div> 
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

		<div class="coinbase"> 
			<a class="coinbase-button" data-code="53bc202556eeda39cc5c91d1feee16c6" data-button-style="custom_large" href="https://coinbase.com/checkouts/53bc202556eeda39cc5c91d1feee16c6">Pay With Bitcoin</a><script src="https://coinbase.com/assets/button.js" type="text/javascript"></script>
		</div> 
		<div class="price">
			<p>One-of-a-kind Space Art</p> 
			<p>Buy Today for .04 BTC</p>
		</div> 

	</div> 

	</div>